// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package order_client

import (
	"context"

	"letsgo/services/order/rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderRequest        = order.CancelOrderRequest
	CancelOrderResponse       = order.CancelOrderResponse
	CreateOrderRequest        = order.CreateOrderRequest
	CreateOrderResponse       = order.CreateOrderResponse
	GetOrderByNoRequest       = order.GetOrderByNoRequest
	GetOrderByNoResponse      = order.GetOrderByNoResponse
	GetOrderRequest           = order.GetOrderRequest
	GetOrderResponse          = order.GetOrderResponse
	ListOrdersRequest         = order.ListOrdersRequest
	ListOrdersResponse        = order.ListOrdersResponse
	OrderInfo                 = order.OrderInfo
	OrderItem                 = order.OrderItem
	UpdateOrderStatusRequest  = order.UpdateOrderStatusRequest
	UpdateOrderStatusResponse = order.UpdateOrderStatusResponse

	Order interface {
		// Create new order from cart
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		// Get order detail
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
		// List user's orders with pagination
		ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
		// Cancel order (only if not paid)
		CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
		// Update order status (called by payment service, shipping system)
		UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error)
		// Get order by order number
		GetOrderByNo(ctx context.Context, in *GetOrderByNoRequest, opts ...grpc.CallOption) (*GetOrderByNoResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// Create new order from cart
func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// Get order detail
func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

// List user's orders with pagination
func (m *defaultOrder) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

// Cancel order (only if not paid)
func (m *defaultOrder) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// Update order status (called by payment service, shipping system)
func (m *defaultOrder) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.UpdateOrderStatus(ctx, in, opts...)
}

// Get order by order number
func (m *defaultOrder) GetOrderByNo(ctx context.Context, in *GetOrderByNoRequest, opts ...grpc.CallOption) (*GetOrderByNoResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderByNo(ctx, in, opts...)
}
