// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package product_client

import (
	"context"

	"letsgo/services/product/rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductRequest      = product.AddProductRequest
	AddProductResponse     = product.AddProductResponse
	CheckStockRequest      = product.CheckStockRequest
	CheckStockResponse     = product.CheckStockResponse
	GetProductRequest      = product.GetProductRequest
	GetProductResponse     = product.GetProductResponse
	IncrementSalesRequest  = product.IncrementSalesRequest
	IncrementSalesResponse = product.IncrementSalesResponse
	ListProductsRequest    = product.ListProductsRequest
	ListProductsResponse   = product.ListProductsResponse
	ProductInfo            = product.ProductInfo
	SearchProductsRequest  = product.SearchProductsRequest
	SearchProductsResponse = product.SearchProductsResponse
	StockItem              = product.StockItem
	UpdateProductRequest   = product.UpdateProductRequest
	UpdateProductResponse  = product.UpdateProductResponse
	UpdateStockRequest     = product.UpdateStockRequest
	UpdateStockResponse    = product.UpdateStockResponse

	Product interface {
		// Add new product (admin)
		AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
		// Update product information (admin)
		UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
		// Get product detail
		GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
		// List products with pagination
		ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
		// Search products by keyword
		SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
		// Update product stock (called by order service)
		UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error)
		// Check if products are in stock (batch check)
		CheckStock(ctx context.Context, in *CheckStockRequest, opts ...grpc.CallOption) (*CheckStockResponse, error)
		// Increment product sales count (called by order service after order completion)
		IncrementSales(ctx context.Context, in *IncrementSalesRequest, opts ...grpc.CallOption) (*IncrementSalesResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

// Add new product (admin)
func (m *defaultProduct) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.AddProduct(ctx, in, opts...)
}

// Update product information (admin)
func (m *defaultProduct) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

// Get product detail
func (m *defaultProduct) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

// List products with pagination
func (m *defaultProduct) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}

// Search products by keyword
func (m *defaultProduct) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.SearchProducts(ctx, in, opts...)
}

// Update product stock (called by order service)
func (m *defaultProduct) UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateStock(ctx, in, opts...)
}

// Check if products are in stock (batch check)
func (m *defaultProduct) CheckStock(ctx context.Context, in *CheckStockRequest, opts ...grpc.CallOption) (*CheckStockResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CheckStock(ctx, in, opts...)
}

// Increment product sales count (called by order service after order completion)
func (m *defaultProduct) IncrementSales(ctx context.Context, in *IncrementSalesRequest, opts ...grpc.CallOption) (*IncrementSalesResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.IncrementSales(ctx, in, opts...)
}
