// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cart.proto

package server

import (
	"context"

	"letsgo/services/cart/rpc/cart"
	"letsgo/services/cart/rpc/internal/logic"
	"letsgo/services/cart/rpc/internal/svc"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

// Add product to cart
func (s *CartServer) AddToCart(ctx context.Context, in *cart.AddToCartRequest) (*cart.AddToCartResponse, error) {
	l := logic.NewAddToCartLogic(ctx, s.svcCtx)
	return l.AddToCart(in)
}

// Get user's cart
func (s *CartServer) GetCart(ctx context.Context, in *cart.GetCartRequest) (*cart.GetCartResponse, error) {
	l := logic.NewGetCartLogic(ctx, s.svcCtx)
	return l.GetCart(in)
}

// Update cart item quantity
func (s *CartServer) UpdateCartItem(ctx context.Context, in *cart.UpdateCartItemRequest) (*cart.UpdateCartItemResponse, error) {
	l := logic.NewUpdateCartItemLogic(ctx, s.svcCtx)
	return l.UpdateCartItem(in)
}

// Remove item from cart
func (s *CartServer) RemoveCartItem(ctx context.Context, in *cart.RemoveCartItemRequest) (*cart.RemoveCartItemResponse, error) {
	l := logic.NewRemoveCartItemLogic(ctx, s.svcCtx)
	return l.RemoveCartItem(in)
}

// Clear entire cart
func (s *CartServer) ClearCart(ctx context.Context, in *cart.ClearCartRequest) (*cart.ClearCartResponse, error) {
	l := logic.NewClearCartLogic(ctx, s.svcCtx)
	return l.ClearCart(in)
}

// Merge guest cart with user cart (after login)
func (s *CartServer) MergeCart(ctx context.Context, in *cart.MergeCartRequest) (*cart.MergeCartResponse, error) {
	l := logic.NewMergeCartLogic(ctx, s.svcCtx)
	return l.MergeCart(in)
}
