// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"letsgo/services/order/rpc/internal/logic"
	"letsgo/services/order/rpc/internal/svc"
	"letsgo/services/order/rpc/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// Create new order from cart
func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// Get order detail
func (s *OrderServer) GetOrder(ctx context.Context, in *order.GetOrderRequest) (*order.GetOrderResponse, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

// List user's orders with pagination
func (s *OrderServer) ListOrders(ctx context.Context, in *order.ListOrdersRequest) (*order.ListOrdersResponse, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

// Cancel order (only if not paid)
func (s *OrderServer) CancelOrder(ctx context.Context, in *order.CancelOrderRequest) (*order.CancelOrderResponse, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

// Update order status (called by payment service, shipping system)
func (s *OrderServer) UpdateOrderStatus(ctx context.Context, in *order.UpdateOrderStatusRequest) (*order.UpdateOrderStatusResponse, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}

// Get order by order number
func (s *OrderServer) GetOrderByNo(ctx context.Context, in *order.GetOrderByNoRequest) (*order.GetOrderByNoResponse, error) {
	l := logic.NewGetOrderByNoLogic(ctx, s.svcCtx)
	return l.GetOrderByNo(in)
}
