-- Active: 1765858635477@@127.0.0.1@5432@letsgo_payment
-- ========================================
-- Payment Tables Migration
-- ========================================
-- This migration creates the tables needed for the payment service

-- ========================================
-- 1. Payments Table (Main payment information)
-- ========================================
CREATE TABLE IF NOT EXISTS payments (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,           -- One payment per order (unique constraint)
    user_id BIGINT NOT NULL,
    payment_no VARCHAR(32) UNIQUE NOT NULL,    -- Unique payment transaction number (e.g., PAY20260108123456789012)
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    payment_type SMALLINT NOT NULL,            -- 1:Alipay, 2:WeChat Pay, 3:Credit Card
    status SMALLINT DEFAULT 1 NOT NULL,        -- 1:pending, 2:success, 3:failed, 4:cancelled
    trade_no VARCHAR(64) DEFAULT '',           -- Third-party transaction number (from Alipay/WeChat)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP,                         -- Actual payment time
    -- Constraints
    CONSTRAINT payments_user_id_check CHECK (user_id > 0),
    CONSTRAINT payments_order_id_check CHECK (order_id > 0),
    CONSTRAINT payments_payment_type_check CHECK (payment_type IN (1, 2, 3)),
    CONSTRAINT payments_status_check CHECK (status IN (1, 2, 3, 4))
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_no ON payments(payment_no);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_user_status ON payments(user_id, status);

-- ========================================
-- 2. Comments and Documentation
-- ========================================
COMMENT ON TABLE payments IS 'Payment records table storing all payment transactions';
COMMENT ON COLUMN payments.order_id IS 'Associated order ID (one-to-one relationship)';
COMMENT ON COLUMN payments.payment_no IS 'Unique payment transaction number generated by system';
COMMENT ON COLUMN payments.payment_type IS '1:Alipay(支付宝), 2:WeChat Pay(微信支付), 3:Credit Card(信用卡)';
COMMENT ON COLUMN payments.status IS '1:pending(待支付), 2:success(成功), 3:failed(失败), 4:cancelled(已取消)';
COMMENT ON COLUMN payments.trade_no IS 'Third-party transaction number from payment gateway';
COMMENT ON COLUMN payments.amount IS 'Payment amount in decimal format';

-- ========================================
-- 3. Updated At Trigger (Auto-update timestamp)
-- ========================================
CREATE OR REPLACE FUNCTION update_payments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION update_payments_updated_at();

-- ========================================
-- 4. Sample Data (Optional - for testing)
-- ========================================
-- Uncomment below to insert test data
/*
INSERT INTO payments (order_id, user_id, payment_no, amount, payment_type, status, trade_no) VALUES
(1, 1, 'PAY20260108123456789012', 599.99, 1, 1, ''),
(2, 1, 'PAY20260108123456789013', 299.50, 2, 2, '2026010822001234567890');
*/
