// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	cart "letsgo/gateway/internal/handler/cart"
	order "letsgo/gateway/internal/handler/order"
	payment "letsgo/gateway/internal/handler/payment"
	product "letsgo/gateway/internal/handler/product"
	user "letsgo/gateway/internal/handler/user"
	"letsgo/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// Get cart - Retrieve user's shopping cart
					Method:  http.MethodGet,
					Path:    "/",
					Handler: cart.GetCartHandler(serverCtx),
				},
				{
					// Add to cart - Add product to shopping cart
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: cart.AddToCartHandler(serverCtx),
				},
				{
					// Clear cart - Remove all items from cart
					Method:  http.MethodDelete,
					Path:    "/clear",
					Handler: cart.ClearCartHandler(serverCtx),
				},
				{
					// Remove from cart - Delete item from cart
					Method:  http.MethodDelete,
					Path:    "/remove/:productId",
					Handler: cart.RemoveFromCartHandler(serverCtx),
				},
				{
					// Update cart item - Change quantity of item in cart
					Method:  http.MethodPut,
					Path:    "/update",
					Handler: cart.UpdateCartHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/cart"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// Cancel order - Cancel pending order
					Method:  http.MethodPut,
					Path:    "/cancel/:id",
					Handler: order.CancelOrderHandler(serverCtx),
				},
				{
					// Create order - Convert cart to order
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: order.CreateOrderHandler(serverCtx),
				},
				{
					// Get order detail - View single order details
					Method:  http.MethodGet,
					Path:    "/detail/:id",
					Handler: order.GetOrderDetailHandler(serverCtx),
				},
				{
					// Get order list - View user's order history
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: order.ListOrdersHandler(serverCtx),
				},
				{
					// Query order by number - Search order by order number
					Method:  http.MethodGet,
					Path:    "/query/:orderNo",
					Handler: order.QueryOrderByNoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/order"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// Create payment - Initiate payment for order
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: payment.CreatePaymentHandler(serverCtx),
				},
				{
					// Query payment status - Check payment result
					Method:  http.MethodGet,
					Path:    "/query/:orderId",
					Handler: payment.QueryPaymentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/payment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Payment callback - Webhook for payment gateway (for testing)
				Method:  http.MethodPost,
				Path:    "/callback",
				Handler: payment.PaymentCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/payment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get product detail - View single product information
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: product.GetProductDetailHandler(serverCtx),
			},
			{
				// List products - Get paginated list of products
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: product.ListProductsHandler(serverCtx),
			},
			{
				// Search products - Search by keyword
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: product.SearchProductsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// Add product - Admin creates new product (admin only)
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: product.AddProductHandler(serverCtx),
				},
				{
					// Update product - Admin modifies product (admin only)
					Method:  http.MethodPut,
					Path:    "/update",
					Handler: product.UpdateProductHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/product"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// User login - Authenticates user and returns JWT token
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// User registration - Creates a new user account
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// Get user profile - Returns current user information
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: user.GetUserProfileHandler(serverCtx),
				},
				{
					// Update user profile - Updates user information
					Method:  http.MethodPut,
					Path:    "/profile",
					Handler: user.UpdateUserProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)
}
