// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package server

import (
	"context"

	"letsgo/services/payment/rpc/internal/logic"
	"letsgo/services/payment/rpc/internal/svc"
	"letsgo/services/payment/rpc/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

// Create payment for order
func (s *PaymentServer) CreatePayment(ctx context.Context, in *payment.CreatePaymentRequest) (*payment.CreatePaymentResponse, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}

// Query payment status
func (s *PaymentServer) QueryPayment(ctx context.Context, in *payment.QueryPaymentRequest) (*payment.QueryPaymentResponse, error) {
	l := logic.NewQueryPaymentLogic(ctx, s.svcCtx)
	return l.QueryPayment(in)
}

// Process payment callback from payment gateway
func (s *PaymentServer) PaymentCallback(ctx context.Context, in *payment.PaymentCallbackRequest) (*payment.PaymentCallbackResponse, error) {
	l := logic.NewPaymentCallbackLogic(ctx, s.svcCtx)
	return l.PaymentCallback(in)
}

// Cancel payment (timeout or user cancellation)
func (s *PaymentServer) CancelPayment(ctx context.Context, in *payment.CancelPaymentRequest) (*payment.CancelPaymentResponse, error) {
	l := logic.NewCancelPaymentLogic(ctx, s.svcCtx)
	return l.CancelPayment(in)
}

// Get payment by order ID
func (s *PaymentServer) GetPaymentByOrderId(ctx context.Context, in *payment.GetPaymentByOrderIdRequest) (*payment.GetPaymentByOrderIdResponse, error) {
	l := logic.NewGetPaymentByOrderIdLogic(ctx, s.svcCtx)
	return l.GetPaymentByOrderId(in)
}
