// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cart.proto

package cart_client

import (
	"context"

	"letsgo/services/cart/rpc/cart"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddToCartRequest       = cart.AddToCartRequest
	AddToCartResponse      = cart.AddToCartResponse
	CartItem               = cart.CartItem
	ClearCartRequest       = cart.ClearCartRequest
	ClearCartResponse      = cart.ClearCartResponse
	GetCartRequest         = cart.GetCartRequest
	GetCartResponse        = cart.GetCartResponse
	MergeCartRequest       = cart.MergeCartRequest
	MergeCartResponse      = cart.MergeCartResponse
	RemoveCartItemRequest  = cart.RemoveCartItemRequest
	RemoveCartItemResponse = cart.RemoveCartItemResponse
	UpdateCartItemRequest  = cart.UpdateCartItemRequest
	UpdateCartItemResponse = cart.UpdateCartItemResponse

	Cart interface {
		// Add product to cart
		AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error)
		// Get user's cart
		GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*GetCartResponse, error)
		// Update cart item quantity
		UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*UpdateCartItemResponse, error)
		// Remove item from cart
		RemoveCartItem(ctx context.Context, in *RemoveCartItemRequest, opts ...grpc.CallOption) (*RemoveCartItemResponse, error)
		// Clear entire cart
		ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*ClearCartResponse, error)
		// Merge guest cart with user cart (after login)
		MergeCart(ctx context.Context, in *MergeCartRequest, opts ...grpc.CallOption) (*MergeCartResponse, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

// Add product to cart
func (m *defaultCart) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.AddToCart(ctx, in, opts...)
}

// Get user's cart
func (m *defaultCart) GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*GetCartResponse, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.GetCart(ctx, in, opts...)
}

// Update cart item quantity
func (m *defaultCart) UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*UpdateCartItemResponse, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.UpdateCartItem(ctx, in, opts...)
}

// Remove item from cart
func (m *defaultCart) RemoveCartItem(ctx context.Context, in *RemoveCartItemRequest, opts ...grpc.CallOption) (*RemoveCartItemResponse, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.RemoveCartItem(ctx, in, opts...)
}

// Clear entire cart
func (m *defaultCart) ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*ClearCartResponse, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.ClearCart(ctx, in, opts...)
}

// Merge guest cart with user cart (after login)
func (m *defaultCart) MergeCart(ctx context.Context, in *MergeCartRequest, opts ...grpc.CallOption) (*MergeCartResponse, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.MergeCart(ctx, in, opts...)
}
