// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddProductReq struct {
	Name        string   `json:"name" validate:"required,min=1,max=200"`
	Description string   `json:"description" validate:"required"`
	Price       float64  `json:"price" validate:"required,gt=0"`  // Must be > 0
	Stock       int64    `json:"stock" validate:"required,gte=0"` // Must be >= 0
	Category    string   `json:"category" validate:"required"`
	Images      []string `json:"images" validate:"required,min=1"` // At least 1 image
	Attributes  string   `json:"attributes,optional"`              // JSON string of attributes
}

type AddProductResp struct {
	ProductId int64 `json:"productId"`
}

type AddToCartReq struct {
	ProductId int64 `json:"productId" validate:"required,min=1"`
	Quantity  int64 `json:"quantity" validate:"required,min=1,max=999"` // 1-999 items
}

type AddToCartResp struct {
	Success bool `json:"success"`
}

type CancelOrderReq struct {
	Id int64 `path:"id" validate:"required,min=1"`
}

type CancelOrderResp struct {
	Success bool `json:"success"`
}

type CartItem struct {
	ProductId int64   `json:"productId"` // Product reference
	Name      string  `json:"name"`
	Price     float64 `json:"price"` // Price at time of adding
	Quantity  int64   `json:"quantity"`
	Image     string  `json:"image"`     // First product image
	Stock     int64   `json:"stock"`     // Current available stock
	Available bool    `json:"available"` // Is product still available
}

type CartResp struct {
	Items      []CartItem `json:"items"`
	TotalPrice float64    `json:"totalPrice"` // Sum of all items
	TotalCount int64      `json:"totalCount"` // Total number of items
}

type ClearCartResp struct {
	Success bool `json:"success"`
}

type CreateOrderReq struct {
	Items   []OrderItemReq `json:"items" validate:"required,min=1,dive"` // At least 1 item
	Address string         `json:"address" validate:"required,min=10"`   // Delivery address
	Phone   string         `json:"phone" validate:"required,len=11"`     // Contact phone
	Remark  string         `json:"remark,optional"`                      // Order notes
}

type CreateOrderResp struct {
	OrderId     int64   `json:"orderId"`
	OrderNo     string  `json:"orderNo"`     // Human-readable order number
	TotalAmount float64 `json:"totalAmount"` // Total order price
}

type CreatePaymentReq struct {
	OrderId     int64   `json:"orderId" validate:"required,min=1"`
	PaymentType int     `json:"paymentType" validate:"required,oneof=1 2 3"` // Payment method
	Amount      float64 `json:"amount" validate:"required,gt=0"`
}

type CreatePaymentResp struct {
	PaymentId int64  `json:"paymentId"`
	PaymentNo string `json:"paymentNo"`       // Payment transaction number
	PayUrl    string `json:"payUrl,optional"` // Payment page URL (for redirect)
	QrCode    string `json:"qrCode,optional"` // QR code for scan payment
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type Order struct {
	Id          int64       `json:"id"`
	UserId      int64       `json:"userId"`
	OrderNo     string      `json:"orderNo"` // e.g., "LG20250104123456"
	TotalAmount float64     `json:"totalAmount"`
	Status      int         `json:"status"` // Order status (see below)
	Address     string      `json:"address"`
	Phone       string      `json:"phone"`
	Remark      string      `json:"remark"`
	Items       []OrderItem `json:"items"` // Order items list
	CreatedAt   int64       `json:"createdAt"`
	UpdatedAt   int64       `json:"updatedAt"`
	PaidAt      int64       `json:"paidAt,optional"`      // Payment time
	ShippedAt   int64       `json:"shippedAt,optional"`   // Shipping time
	CompletedAt int64       `json:"completedAt,optional"` // Completion time
}

type OrderDetailReq struct {
	Id int64 `path:"id" validate:"required,min=1"`
}

type OrderDetailResp struct {
	Order Order `json:"order"`
}

type OrderItem struct {
	Id        int64   `json:"id"`
	ProductId int64   `json:"productId"`
	Name      string  `json:"name"`
	Price     float64 `json:"price"` // Price at time of purchase (snapshot)
	Quantity  int64   `json:"quantity"`
	Image     string  `json:"image"`
}

type OrderItemReq struct {
	ProductId int64 `json:"productId" validate:"required,min=1"`
	Quantity  int64 `json:"quantity" validate:"required,min=1"`
}

type OrderListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=10"`
	Status   int `form:"status,optional"` // Filter by status (0=all)
}

type OrderListResp struct {
	Total  int64   `json:"total"`
	Orders []Order `json:"orders"`
}

type PaymentCallbackReq struct {
	PaymentNo string  `json:"paymentNo" validate:"required"`
	OrderId   int64   `json:"orderId" validate:"required"`
	Status    int     `json:"status" validate:"required"`
	Amount    float64 `json:"amount" validate:"required"`
	TradeNo   string  `json:"tradeNo"` // Third-party transaction number
}

type PaymentCallbackResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Product struct {
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Price       float64  `json:"price"`
	Stock       int64    `json:"stock"`
	Category    string   `json:"category"`
	Images      []string `json:"images"`     // Array of image URLs
	Attributes  string   `json:"attributes"` // JSON string: {"color": "red", "size": "L"}
	Sales       int64    `json:"sales"`      // Total sales count
	CreatedAt   int64    `json:"createdAt"`
	UpdatedAt   int64    `json:"updatedAt"`
}

type ProductDetailReq struct {
	Id int64 `path:"id" validate:"required,min=1"` // Product ID from URL path
}

type ProductDetailResp struct {
	Product Product `json:"product"`
}

type ProductListReq struct {
	Page     int    `form:"page,default=1"`                              // Current page number
	PageSize int    `form:"pageSize,default=20"`                         // Items per page
	Category string `form:"category,optional"`                           // Filter by category
	SortBy   string `form:"sortBy,optional,options=price|created|sales"` // Sort field
	Order    string `form:"order,optional,options=asc|desc"`             // Sort order
}

type ProductListResp struct {
	Total    int64     `json:"total"`    // Total number of products
	Products []Product `json:"products"` // Product list
}

type ProductSearchReq struct {
	Keyword  string `form:"keyword" validate:"required,min=1"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
}

type ProductSearchResp struct {
	Total    int64     `json:"total"`
	Products []Product `json:"products"`
}

type QueryPaymentReq struct {
	OrderId int64 `path:"orderId" validate:"required,min=1"`
}

type QueryPaymentResp struct {
	PaymentId   int64   `json:"paymentId"`
	PaymentNo   string  `json:"paymentNo"`
	OrderId     int64   `json:"orderId"`
	Status      int     `json:"status"` // Payment status (see below)
	Amount      float64 `json:"amount"`
	PaymentType int     `json:"paymentType"`
	PaidAt      int64   `json:"paidAt,optional"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=20"`  // Username 3-20 chars
	Password string `json:"password" validate:"required,min=6"`         // Password min 6 chars
	Email    string `json:"email" validate:"required,email"`            // Valid email format
	Phone    string `json:"phone,optional" validate:"omitempty,len=11"` // Optional 11-digit phone
}

type RegisterResp struct {
	UserId int64  `json:"userId"` // Unique user identifier
	Token  string `json:"token"`  // JWT authentication token
}

type RemoveCartReq struct {
	ProductId int64 `path:"productId" validate:"required,min=1"`
}

type RemoveCartResp struct {
	Success bool `json:"success"`
}

type UpdateCartReq struct {
	ProductId int64 `json:"productId" validate:"required,min=1"`
	Quantity  int64 `json:"quantity" validate:"required,min=1,max=999"`
}

type UpdateCartResp struct {
	Success bool `json:"success"`
}

type UpdateProductReq struct {
	Id          int64    `json:"id" validate:"required"`
	Name        string   `json:"name,optional" validate:"omitempty,min=1,max=200"`
	Description string   `json:"description,optional"`
	Price       float64  `json:"price,optional" validate:"omitempty,gt=0"`
	Category    string   `json:"category,optional"`
	Images      []string `json:"images,optional"`
	Attributes  string   `json:"attributes,optional"`
}

type UpdateProductResp struct {
	Success bool `json:"success"`
}

type UpdateProfileReq struct {
	Email  string `json:"email,optional" validate:"omitempty,email"`
	Phone  string `json:"phone,optional" validate:"omitempty,len=11"`
	Avatar string `json:"avatar,optional"`
}

type UpdateProfileResp struct {
	Success bool `json:"success"`
}

type UserProfileResp struct {
	UserId    int64  `json:"userId"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Avatar    string `json:"avatar"`
	CreatedAt int64  `json:"createdAt"` // Unix timestamp
}
