// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package payment_client

import (
	"context"

	"letsgo/services/payment/rpc/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelPaymentRequest        = payment.CancelPaymentRequest
	CancelPaymentResponse       = payment.CancelPaymentResponse
	CreatePaymentRequest        = payment.CreatePaymentRequest
	CreatePaymentResponse       = payment.CreatePaymentResponse
	GetPaymentByOrderIdRequest  = payment.GetPaymentByOrderIdRequest
	GetPaymentByOrderIdResponse = payment.GetPaymentByOrderIdResponse
	PaymentCallbackRequest      = payment.PaymentCallbackRequest
	PaymentCallbackResponse     = payment.PaymentCallbackResponse
	PaymentInfo                 = payment.PaymentInfo
	QueryPaymentRequest         = payment.QueryPaymentRequest
	QueryPaymentResponse        = payment.QueryPaymentResponse

	Payment interface {
		// Create payment for order
		CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
		// Query payment status
		QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error)
		// Process payment callback from payment gateway
		PaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error)
		// Cancel payment (timeout or user cancellation)
		CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error)
		// Get payment by order ID
		GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, opts ...grpc.CallOption) (*GetPaymentByOrderIdResponse, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

// Create payment for order
func (m *defaultPayment) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

// Query payment status
func (m *defaultPayment) QueryPayment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.QueryPayment(ctx, in, opts...)
}

// Process payment callback from payment gateway
func (m *defaultPayment) PaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.PaymentCallback(ctx, in, opts...)
}

// Cancel payment (timeout or user cancellation)
func (m *defaultPayment) CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.CancelPayment(ctx, in, opts...)
}

// Get payment by order ID
func (m *defaultPayment) GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, opts ...grpc.CallOption) (*GetPaymentByOrderIdResponse, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.GetPaymentByOrderId(ctx, in, opts...)
}
