// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user_client

import (
	"context"

	"letsgo/services/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserInfoRequest    = user.GetUserInfoRequest
	GetUserInfoResponse   = user.GetUserInfoResponse
	LoginRequest          = user.LoginRequest
	LoginResponse         = user.LoginResponse
	RegisterRequest       = user.RegisterRequest
	RegisterResponse      = user.RegisterResponse
	UpdateProfileRequest  = user.UpdateProfileRequest
	UpdateProfileResponse = user.UpdateProfileResponse
	VerifyTokenRequest    = user.VerifyTokenRequest
	VerifyTokenResponse   = user.VerifyTokenResponse

	User interface {
		// Register a new user account
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		// Login and get JWT token
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// Get user information by user ID
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		// Update user profile
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
		// Verify JWT token validity
		VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// Register a new user account
func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// Login and get JWT token
func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// Get user information by user ID
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// Update user profile
func (m *defaultUser) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

// Verify JWT token validity
func (m *defaultUser) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}
