// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package server

import (
	"context"

	"letsgo/services/product/rpc/internal/logic"
	"letsgo/services/product/rpc/internal/svc"
	"letsgo/services/product/rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

// Add new product (admin)
func (s *ProductServer) AddProduct(ctx context.Context, in *product.AddProductRequest) (*product.AddProductResponse, error) {
	l := logic.NewAddProductLogic(ctx, s.svcCtx)
	return l.AddProduct(in)
}

// Update product information (admin)
func (s *ProductServer) UpdateProduct(ctx context.Context, in *product.UpdateProductRequest) (*product.UpdateProductResponse, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

// Get product detail
func (s *ProductServer) GetProduct(ctx context.Context, in *product.GetProductRequest) (*product.GetProductResponse, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

// List products with pagination
func (s *ProductServer) ListProducts(ctx context.Context, in *product.ListProductsRequest) (*product.ListProductsResponse, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

// Search products by keyword
func (s *ProductServer) SearchProducts(ctx context.Context, in *product.SearchProductsRequest) (*product.SearchProductsResponse, error) {
	l := logic.NewSearchProductsLogic(ctx, s.svcCtx)
	return l.SearchProducts(in)
}

// Update product stock (called by order service)
func (s *ProductServer) UpdateStock(ctx context.Context, in *product.UpdateStockRequest) (*product.UpdateStockResponse, error) {
	l := logic.NewUpdateStockLogic(ctx, s.svcCtx)
	return l.UpdateStock(in)
}

// Check if products are in stock (batch check)
func (s *ProductServer) CheckStock(ctx context.Context, in *product.CheckStockRequest) (*product.CheckStockResponse, error) {
	l := logic.NewCheckStockLogic(ctx, s.svcCtx)
	return l.CheckStock(in)
}

// Increment product sales count (called by order service after order completion)
func (s *ProductServer) IncrementSales(ctx context.Context, in *product.IncrementSalesRequest) (*product.IncrementSalesResponse, error) {
	l := logic.NewIncrementSalesLogic(ctx, s.svcCtx)
	return l.IncrementSales(in)
}
